n = 20;
% v = (1:n)'*(1:n)/n^2;
v = rand(n);
v = v(:);
p = 3;
cost1 = afkookt(v,p);
cost1 = reshape(cost1,n,n);
figure; heatmap(cost1);
cost2 = fin_dif(v(:),p,1e-6);
cost2 = reshape(cost2,n,n);
figure; heatmap(cost2);
err = abs(cost2-cost1)./(abs(cost1)+1);
figure; heatmap(err);